### ISSUE TITLE
Add MD5 checksums and warning about Google Safe Browsing

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Hunter-Raff/e-ReaderCardCreator#4]

**Comment by imaemii** [comment]
???

**Comment by TheSystemGuy1337** [comment]
Adding 3 question marks is not enough context. Therefore I will add context. Since this program is brand new - any attempt to download it will automatically be blocked by Google’s Safe Browsing service. And with any open source project, it is wise to add checksums, it could have been tampered with while you where downloading it

**Comment by HunterRDev** [comment]
I knew what you meant. I'll get around to fixing reported issues/suggestions soon.
